import './globals.scss'

export const metadata = {
  title: 'Tuki - La Cosa',
  description: 'Generated by create next app',
}

export default function RootLayout({ className, children }) {
  return (
    <html lang="en">
      <body className={className}>
        {children}
      </body>
    </html>
  )
}
