'use client'

import './globals.scss'
import { WebSocketProvider } from '@/services/WebSocketContext'
import { UserGameProvider } from '@/services/UserGameContext'

// export const metadata = {
//   title: 'Tuki - La Cosa',
//   description: 'Generated by create next app',
// }

function RootLayout ({ className, children }) {
  return (
    <WebSocketProvider>
      <UserGameProvider>
        <html lang='en'>
          <body className={className}>
            {children}
          </body>
        </html>
      </UserGameProvider>
    </WebSocketProvider>
  )
}

export default RootLayout
